import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FBFAF8',
  },
  keyboardShell: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 20,
  },
  glowOne: {
    position: 'absolute',
    top: -90,
    left: -100,
    width: 260,
    height: 260,
    borderRadius: 260,
    backgroundColor: 'rgba(235, 205, 182, 0.18)',
  },
  glowTwo: {
    position: 'absolute',
    top: 110,
    right: -120,
    width: 240,
    height: 240,
    borderRadius: 240,
    backgroundColor: 'rgba(241, 232, 224, 0.50)',
  },
  glowThree: {
    position: 'absolute',
    bottom: 120,
    left: -60,
    width: 180,
    height: 180,
    borderRadius: 180,
    backgroundColor: 'rgba(226, 211, 198, 0.16)',
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 30,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#EFE8E2',
    backgroundColor: 'rgba(255,255,255,0.42)',
  },
  brandText: {
    marginLeft: 8,
    fontSize: 22,
    fontWeight: '800',
    color: '#A44A12',
  },
  heroArea: {
    alignItems: 'center',
    paddingTop: 92,
    paddingHorizontal: 24,
  },
  heroIconBox: {
    width: 104,
    height: 104,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderWidth: 1,
    borderColor: '#F0E8E1',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#D8CFC6',
    shadowOpacity: 0.42,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  heroTitle: {
    marginTop: 34,
    fontSize: 35,
    lineHeight: 40,
    fontWeight: '900',
    color: '#111111',
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  heroSubtitle: {
    marginTop: 10,
    maxWidth: 320,
    fontSize: 16,
    lineHeight: 24,
    color: '#6F645B',
    textAlign: 'center',
  },
  formCard: {
    marginTop: 34,
    marginHorizontal: 16,
    paddingHorizontal: 20,
    paddingTop: 22,
    paddingBottom: 24,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderWidth: 1,
    borderColor: '#F0E7DF',
    shadowColor: '#CDBFB2',
    shadowOpacity: 0.14,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 1,
  },
  fieldBlock: {
    marginBottom: 16,
  },
  label: {
    marginBottom: 10,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '700',
    color: '#2A211B',
  },
  fieldBox: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 54,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#D8C8BD',
    backgroundColor: '#F7F6F4',
    paddingHorizontal: 12,
  },
  fieldLeftIcon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    fontSize: 18,
    color: '#3A2E28',
    paddingVertical: 0,
  },
  eyeHitbox: {
    paddingLeft: 10,
    paddingVertical: 6,
    paddingRight: 2,
  },
  forgotWrap: {
    alignSelf: 'flex-end',
    marginTop: 2,
    marginBottom: 18,
  },
  forgotText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#A44A12',
  },
  loginButton: {
    height: 54,
    borderRadius: 4,
    backgroundColor: '#F47920',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#C85A0E',
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  loginButtonDisabled: {
    opacity: 0.85,
  },
  loginText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 18,
    marginBottom: 18,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#D6CEC5',
  },
  dividerText: {
    marginHorizontal: 12,
    fontSize: 14,
    fontWeight: '700',
    color: '#6D6258',
  },
  googleButton: {
    height: 54,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#365D85',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  googleIcon: {
    width: 24,
    height: 24,
    marginRight: 12,
    borderRadius: 3,
  },
  googleText: {
    fontSize: 18,
    color: '#365D85',
    fontWeight: '700',
  },
  noticeCard: {
    marginTop: 28,
    marginHorizontal: 16,
    flexDirection: 'row',
    backgroundColor: '#F7ECE4',
    borderRadius: 4,
    shadowColor: '#D9C5B7',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 1,
  },
  noticeAccent: {
    width: 4,
    backgroundColor: '#A44A12',
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
  },
  noticeBodyWrap: {
    flex: 1,
    paddingVertical: 18,
    paddingHorizontal: 14,
  },
  noticeHeadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  noticeTitle: {
    marginLeft: 8,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '800',
    color: '#1C1310',
  },
  noticeBody: {
    fontSize: 16,
    lineHeight: 22,
    color: '#5D4A40',
  },
  footer: {
    alignItems: 'center',
    paddingTop: 84,
    paddingHorizontal: 18,
  },
  footerCopy: {
    fontSize: 13,
    color: '#79716A',
    textAlign: 'center',
    marginBottom: 16,
  },
  footerLinks: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  footerLink: {
    marginHorizontal: 8,
    fontSize: 15,
    color: '#6A625D',
    textDecorationLine: 'underline',
  },
});
